// This file is autogenerated by the App Prototyper.
// Do not edit this file directly.
// For more information, see https://firebase.google.com/docs/studio

export const AP_PROJECT_ID = 'intelibank';
export const AP_PROJECT_NUMBER = '388063551963';
export const AP_WEB_API_KEY = 'AIzaSyCd1rDBqIMnwbMFsC1CEs5t8JWZeC2K1Fc';
export const AP_WEB_APP_ID = '1:388063551963:web:44309f9bcfc8cfc13607fe';
